
export const strings = {
    companyName: "Smart Security",
    login : "Login",
    monitorization: "Monitorization",
    goto: "Go To",
    alarms: "Alarms",
    users: "Users",
    user: "User",
    email: "Email address",
    emailPlaceolder: "example@mail.com",
    password: "Password",
    passwordPlaceholder: "Password",
    role: "Role",
    floor: "Floor",
    groundFloor: "Ground Floor",
    leaveBuilding: "Leave Building",
    logout: "Logout",
    signin: "Sign In",
    managenment: "Managenment",
    adduser: "Add User",
    add: "Add",
}